name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: main
        run: |
          rm -rf src
          git clone https://github.com/kreatolinux/src
          cd src
          make deps
          make chkupd
          mv out/chkupd /tmp/
          rm -rf src
          /tmp/chkupd checkAll --jsonPath=/tmp/chkupd.json --repo="$GITHUB_WORKSPACE"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
      
      - uses: actions/upload-artifact@v3
        with:
          name: json
          path: /tmp/chkupd.json
